"""V1 observation authority, closed envelopes and pinned V1/V3 compatibility."""
from copy import deepcopy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

import jsonschema
import pytest

from test_pdf_pipeline_vision_context_render import make_context_case, render
from test_pdf_pipeline_vision_render import output_file
from test_vision_context_contract import png
from tools.vision import (
    VisionContractError,
    build_vision_context_inspection_request,
    build_vision_context_observation as build,
    build_vision_inspection_request,
    build_vision_observation as build_v3,
    validate_vision_context_inspection_request,
    validate_vision_context_observation as validate,
)


# Complete V3 outputs were generated by contract.py from base 73a739d, not
# by the new observation implementation. The V1 request is pinned from Phase 5E.
GOLDEN = json.loads(Path('tests/fixtures/vision_context_observation_golden.json').read_text())
SCHEMA = json.loads(Path('schema/vision_context_observation_v1.schema.json').read_text())
V3_SCHEMA = json.loads(Path('schema/vision_observation_v1.schema.json').read_text())
REQUEST_SCHEMA = json.loads(Path('schema/vision_context_inspection_request_v1.schema.json').read_text())
STATUSES = ('supported', 'conflict', 'ambiguous', 'insufficient_evidence', 'unresolved')
TEXT = '  電気錠は判別できません。\nKeep original text.\n'


def canonical(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False,
                      separators=(',', ':'), allow_nan=False)


def content_id(prefix, envelope, field):
    content = {key: value for key, value in envelope.items() if key != field}
    return prefix + hashlib.sha256(canonical(content).encode('utf-8')).hexdigest()


def schema_accepts(value, *, with_format=True):
    jsonschema.validate(value, SCHEMA,
                        format_checker=jsonschema.FormatChecker() if with_format else None)


@pytest.fixture
def v1_request():
    return deepcopy(GOLDEN['v1_request'])


@pytest.fixture
def observation(v1_request):
    return build(v1_request, '  provider\n', 'model 日本語', TEXT, 'unresolved', provider_run_id=' run-1 ')


@pytest.mark.parametrize('status', STATUSES)
def test_all_statuses_preserve_original_text_and_complete_evidence(v1_request, status):
    original = deepcopy(v1_request)
    result = build(v1_request, '  provider\n', 'model 日本語', TEXT, status, provider_run_id=' run-1 ')
    assert result == {
        'contract_version': 1, 'kind': 'vision_context_observation',
        'observation_id': content_id('vision-context-observation-', result, 'observation_id'),
        'evidence_class': 'vision_observation', 'request': original,
        'provider': '  provider\n', 'model': 'model 日本語', 'observation': TEXT,
        'status': status, 'provider_run_id': ' run-1 ', 'created_at': None,
    }
    assert v1_request == original
    assert result['request'] is not v1_request
    assert validate(result) == result
    schema_accepts(result)
    assert build(v1_request, '  provider\n', 'model 日本語', TEXT, status, provider_run_id=' run-1 ') == result


def test_ids_are_deterministic_across_json_roundtrip_and_processes(observation, tmp_path):
    assert validate(json.loads(canonical(observation))) == observation
    assert observation['observation_id'] == content_id(
        'vision-context-observation-', observation, 'observation_id')
    record = tmp_path / 'observation.json'
    record.write_text(canonical(observation), encoding='utf-8')
    script = ('import json,sys; from tools.vision import build_vision_context_observation as b; '
              'o=json.load(open(sys.argv[1])); r=b(o["request"],o["provider"],o["model"],'
              'o["observation"],o["status"],provider_run_id=o["provider_run_id"],created_at=o["created_at"]); '
              'print(json.dumps(r,ensure_ascii=False))')
    outputs = []
    for seed in ('1', '2'):
        completed = subprocess.run([sys.executable, '-S', '-c', script, str(record)],
                                   env=dict(os.environ, PYTHONHASHSEED=seed),
                                   check=True, text=True, capture_output=True)
        assert json.loads(completed.stdout) == observation
        outputs.append(completed.stdout)
    assert outputs[0] == outputs[1]


@pytest.mark.parametrize('field,value', [
    ('provider', 'other'), ('model', 'other'), ('observation', TEXT + '追加'),
    ('status', 'conflict'), ('provider_run_id', 'run-2'),
    ('created_at', '2026-10-04T01:11:00Z'),
])
def test_supplied_provider_fields_change_identity(v1_request, observation, field, value):
    params = dict(provider=observation['provider'], model=observation['model'],
                  observation=observation['observation'], status=observation['status'],
                  provider_run_id=observation['provider_run_id'], created_at=observation['created_at'])
    params[field] = value
    result = build(v1_request, **params)
    assert result['observation_id'] != observation['observation_id']
    assert result[field] == value
    assert result['request'] == observation['request']
    schema_accepts(result)


def test_timestamp_representation_preserved_in_identity(v1_request):
    first = build(v1_request, 'p', 'm', TEXT, 'supported', created_at='2026-10-04T01:11:00Z')
    same_instant = build(v1_request, 'p', 'm', TEXT, 'supported', created_at='2026-10-04T01:11:00+00:00')
    assert first['observation_id'] != same_instant['observation_id']
    assert first['created_at'].endswith('Z')
    assert same_instant['created_at'].endswith('+00:00')


@pytest.mark.parametrize('field', ['instruction', 'candidate_id', 'document', 'pdf_page',
                                  'evidence_bbox', 'context_bbox', 'dpi', 'renderer', 'output_sha256'])
def test_validated_request_changes_observation_identity(v1_request, observation, field):
    if field == 'document':
        v1_request['document']['source_sha256'] = '3'*64
    elif field == 'renderer':
        v1_request['renderer']['library_version'] = 'future-version'
    elif field == 'candidate_id':
        v1_request[field] = 'vision-candidate-' + '3'*64
    elif field == 'output_sha256':
        v1_request[field] = '3'*64
    elif field == 'instruction':
        v1_request[field] += '追加'
    elif field == 'evidence_bbox':
        v1_request['evidence_bbox'][0] += 1
        v1_request['context_bbox'][0] += 1
    elif field == 'context_bbox':
        v1_request['evidence_bbox'][0] = 100
        v1_request['context_bbox'][0] = 0
        v1_request['clamped_edges'] = ['left']
    else:
        v1_request[field] += 1
    v1_request['request_id'] = content_id('vision-context-request-', v1_request, 'request_id')
    validate_vision_context_inspection_request(v1_request)
    result = build(v1_request, observation['provider'], observation['model'], TEXT,
                   observation['status'], provider_run_id=observation['provider_run_id'])
    assert result['request'] == v1_request
    assert result['observation_id'] != observation['observation_id']


def test_nested_request_deep_copy_and_tamper_rejection(v1_request, observation):
    before = deepcopy(observation)
    v1_request['document']['source_sha256'] = '4'*64
    v1_request['evidence_bbox'][0] += 1
    v1_request['renderer']['library_version'] = 'mutated'
    v1_request['clamped_edges'].append('left')
    assert observation == before
    isolated = validate(observation)
    isolated['request']['document']['id'] = 'mutated'
    isolated['request']['context_bbox'][0] += 1
    assert observation == before
    with pytest.raises(VisionContractError):
        validate(isolated)
    # Rehashing only the observation cannot bypass nested request validation.
    isolated['observation_id'] = content_id('vision-context-observation-', isolated, 'observation_id')
    with pytest.raises(VisionContractError, match='request ID mismatch|fixed margin'):
        validate(isolated)
    changed = deepcopy(observation)
    changed['observation'] += 'tampered'
    with pytest.raises(VisionContractError, match='observation ID mismatch'):
        validate(changed)


@pytest.mark.parametrize('field', ['provider', 'model', 'observation'])
@pytest.mark.parametrize('value', ['', ' \n', None, 123, True, {}, ['text']])
def test_nonempty_strings_required_in_builder_runtime_and_schema(v1_request, observation, field, value):
    params = dict(provider='p', model='m', observation=TEXT, status='supported', provider_run_id='run')
    params[field] = value
    with pytest.raises(VisionContractError):
        build(v1_request, **params)
    changed = dict(observation, **{field: value})
    with pytest.raises(VisionContractError):
        validate(changed)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(changed)


@pytest.mark.parametrize('status', ['ok', 'pass', 'fail', 'approved', 'source_fact', '', None, True, 1, {}, []])
def test_status_is_closed(v1_request, observation, status):
    with pytest.raises(VisionContractError):
        build(v1_request, 'p', 'm', TEXT, status, provider_run_id='run')
    changed = dict(observation, status=status)
    with pytest.raises(VisionContractError):
        validate(changed)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(changed)


@pytest.mark.parametrize('kwargs', [
    {}, {'provider_run_id': None, 'created_at': None},
    {'provider_run_id': ''}, {'provider_run_id': ' \n'}, {'provider_run_id': 123},
    {'provider_run_id': {}, 'created_at': '2026-10-04T01:11:00Z'},
    {'provider_run_id': '', 'created_at': '2026-10-04T01:11:00Z'},
    {'provider_run_id': 'run', 'created_at': ''},
    {'provider_run_id': 'run', 'created_at': 123},
    {'provider_run_id': 'run', 'created_at': '2026-10-04T01:11:00'},
])
def test_run_or_time_required_and_invalid_values_never_masked(v1_request, observation, kwargs):
    with pytest.raises(VisionContractError):
        build(v1_request, 'p', 'm', TEXT, 'supported', **kwargs)
    changed = dict(observation, provider_run_id=None, created_at=None)
    changed.update(kwargs)
    with pytest.raises(VisionContractError):
        validate(changed)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(changed)


@pytest.mark.parametrize('kwargs', [
    {'provider_run_id': ' run '}, {'created_at': '2026-10-04T01:11:00Z'},
    {'provider_run_id': 'run', 'created_at': '2026-10-04T01:11:00.123456789+09:00'},
])
def test_explicit_run_time_without_defaults(v1_request, kwargs):
    result = build(v1_request, 'p', 'm', TEXT, 'supported', **kwargs)
    assert result['provider_run_id'] == kwargs.get('provider_run_id')
    assert result['created_at'] == kwargs.get('created_at')
    schema_accepts(result)
    assert validate(result) == result


VALID_TIMES = [
    '2026-10-03T00:00:00Z', '2026-10-03T00:00:00+09:00', '2026-10-03T00:00:00-09:00',
    '2026-10-03T00:00:00.123456789Z', '2024-02-29T23:59:59+00:00',
    '2000-02-29T00:00:00Z', '0001-01-01T00:00:00Z', '9999-12-31T23:59:59-23:59',
]
INVALID_TIMES = [
    '2026-10-03T00:00:00', '2026-10-03T00:00:00+0900', '2026-10-03T00:00:00+09:00:00',
    '2026-10-03T00:00:00+09:00:30', '2026-10-03T00:00:00+09:00:00.5', '2026-10-03T00:00:00+09',
    '2026-10-03 00:00:00Z', '20261003T000000Z', '2026-10-03T00:00:00,5Z', '2026-10-03t00:00:00z',
    '2026-02-29T00:00:00Z', '1900-02-29T00:00:00Z', '0000-01-01T00:00:00Z',
    '2026-04-31T00:00:00Z', '2026-10-03T24:00:00Z', '2026-10-03T00:00:60Z',
    '2026-10-03T00:00:00+24:00', '2026-10-03T00:00:00+09:60', '2026-10-03T00:00:00Z\n',
]


@pytest.mark.parametrize('created_at', VALID_TIMES)
@pytest.mark.parametrize('status', STATUSES)
def test_timestamp_v3_runtime_and_schema_acceptance_boundary(v1_request, created_at, status):
    result = build(v1_request, 'p', 'm', TEXT, status, created_at=created_at)
    assert result['created_at'] == created_at
    assert validate(result) == result
    schema_accepts(result)
    schema_accepts(result, with_format=False)
    v3 = build_v3(GOLDEN['v3_region_request'], 'p', 'm', TEXT, status, created_at=created_at)
    jsonschema.validate(v3, V3_SCHEMA, format_checker=jsonschema.FormatChecker())


@pytest.mark.parametrize('created_at', INVALID_TIMES)
def test_timestamp_v3_runtime_and_schema_rejection_boundary(v1_request, observation, created_at):
    for builder, evidence in ((build, v1_request), (build_v3, GOLDEN['v3_region_request'])):
        with pytest.raises(VisionContractError):
            builder(evidence, 'p', 'm', TEXT, 'supported', provider_run_id='run', created_at=created_at)
    changed = dict(observation, created_at=created_at)
    with pytest.raises(VisionContractError):
        validate(changed)
    for with_format in (False, True):
        with pytest.raises(jsonschema.ValidationError):
            schema_accepts(changed, with_format=with_format)


@pytest.mark.parametrize('field,value', [
    ('run_id', 'legacy'), ('confidence', 0.9), ('probability', 0.9), ('approved', True),
    ('pass', True), ('response', {'choices': []}), ('provider_response', {'content': 'text'}),
    ('source_sha256', '4'*64), ('pdf_page', 2), ('evidence_bbox', [0,0,1,1]),
    ('context_bbox', [0,0,2,2]), ('policy', 'fixed_margin_v1'), ('renderer', {}),
    ('output_sha256', '4'*64), ('stage', 'V1'), ('unknown', None),
])
def test_no_legacy_provider_specific_or_evidence_override_fields(v1_request, observation, field, value):
    with pytest.raises(TypeError):
        build(v1_request, 'p', 'm', TEXT, 'supported', provider_run_id='run', **{field: value})
    changed = dict(observation, **{field: value})
    with pytest.raises(VisionContractError):
        validate(changed)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(changed)


def test_no_legacy_run_id_alias(observation):
    legacy = deepcopy(observation)
    legacy['run_id'] = legacy.pop('provider_run_id')
    with pytest.raises(VisionContractError):
        validate(legacy)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(legacy)


@pytest.mark.parametrize('field,value', [('contract_version', True), ('contract_version', 2),
                                       ('kind', 'vision_observation'), ('evidence_class', 'source_fact'),
                                       ('observation_id', 'bad'), ('observation_id', None)])
def test_fixed_envelope_metadata(observation, field, value):
    changed = dict(observation, **{field: value})
    with pytest.raises(VisionContractError):
        validate(changed)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(changed)


def test_schema_is_self_contained_closed_and_exact_request_shape(observation):
    jsonschema.Draft202012Validator.check_schema(SCHEMA)
    assert SCHEMA['properties']['request'] == REQUEST_SCHEMA
    assert SCHEMA['properties']['created_at'] == V3_SCHEMA['properties']['created_at']
    for field in SCHEMA['required']:
        changed = deepcopy(observation)
        del changed[field]
        with pytest.raises(VisionContractError):
            validate(changed)
        with pytest.raises(jsonschema.ValidationError):
            schema_accepts(changed)
    for field in REQUEST_SCHEMA['required']:
        changed = deepcopy(observation)
        del changed['request'][field]
        with pytest.raises(VisionContractError):
            validate(changed)
        with pytest.raises(jsonschema.ValidationError):
            schema_accepts(changed)
    for field, value in [('bbox', [0,0,1,1]), ('confidence', 0.9), ('provider_response', {}),
                         ('policy', 'other'), ('stage', 'V3')]:
        changed = deepcopy(observation)
        changed['request'][field] = value
        with pytest.raises(VisionContractError):
            validate(changed)
        with pytest.raises(jsonschema.ValidationError):
            schema_accepts(changed)


@pytest.mark.parametrize('value', [None, [], 'text', 123, {}])
def test_invalid_request_or_envelope_type(value):
    with pytest.raises(VisionContractError):
        build(value, 'p', 'm', TEXT, 'supported', provider_run_id='run')
    with pytest.raises(VisionContractError):
        validate(value)


def test_tampered_request_never_rehashed_by_builder(v1_request):
    v1_request['document']['source_sha256'] = '4'*64
    with pytest.raises(VisionContractError, match='request ID mismatch'):
        build(v1_request, 'p', 'm', TEXT, 'supported', provider_run_id='run')


def test_cross_rejection_preserves_v1_v3_boundaries(v1_request, observation):
    with pytest.raises(VisionContractError):
        build(GOLDEN['v3_region_request'], 'p', 'm', TEXT, 'supported', provider_run_id='run')
    with pytest.raises(VisionContractError):
        build_v3(v1_request, 'p', 'm', TEXT, 'supported', provider_run_id='run')
    with pytest.raises(VisionContractError):
        validate(GOLDEN['v3_region_observation'])
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(GOLDEN['v3_region_observation'])
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(observation, V3_SCHEMA)
    forged = deepcopy(observation)
    forged['request'] = GOLDEN['v3_region_request']
    with pytest.raises(VisionContractError):
        validate(forged)
    with pytest.raises(jsonschema.ValidationError):
        schema_accepts(forged)


def render_result_from_request(evidence):
    return dict(status='ok', **{key: deepcopy(value) for key, value in evidence.items()
                               if key not in ('contract_version', 'kind', 'request_id', 'instruction', 'stage')})


def test_pinned_phase_5e_request_output_and_id(tmp_path):
    image = tmp_path / 'image.png'
    image.write_bytes(png())
    expected = GOLDEN['v1_request']
    result = render_result_from_request(expected)
    result['stage'] = 'V1'
    actual = build_vision_context_inspection_request(result, image, expected['instruction'])
    assert actual == expected
    assert actual['request_id'] == 'vision-context-request-be817a0712ec991bd1cef01f7bef31b5a95436bce08eb7996556ad3b512da10b'


@pytest.mark.parametrize('scope', ['page', 'region'])
def test_pinned_v3_complete_request_observation_outputs_and_ids(tmp_path, scope):
    image = tmp_path / 'image.png'
    image.write_bytes(png())
    expected_request = GOLDEN['v3_' + scope + '_request']
    result = render_result_from_request(expected_request)
    v3_request = build_vision_inspection_request(result, image, expected_request['instruction'])
    assert v3_request == expected_request
    expected = GOLDEN['v3_' + scope + '_observation']
    actual = build_v3(v3_request, expected['provider'], expected['model'], expected['observation'], expected['status'],
                      provider_run_id=expected['provider_run_id'], created_at=expected['created_at'])
    assert actual == expected
    jsonschema.validate(actual, V3_SCHEMA, format_checker=jsonschema.FormatChecker())


def test_real_db_pdf_png_inputs_are_unchanged_and_observation_has_no_io(tmp_path, monkeypatch):
    source = make_context_case(tmp_path)
    result = render(source, dpi=72)
    image = output_file(source, result)
    v1_request = build_vision_context_inspection_request(result, image, 'Inspect 電気錠')
    paths = (source['database'], source['pdf'], image)
    before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in paths}
    files = sorted(tmp_path.rglob('*'))
    def forbid_read(*args, **kwargs):
        raise AssertionError('observation contracts must not perform file I/O')
    with monkeypatch.context() as blocked:
        blocked.setattr(Path, 'read_bytes', forbid_read)
        blocked.setattr(Path, 'read_text', forbid_read)
        blocked.setattr(Path, 'write_bytes', forbid_read)
        blocked.setattr(Path, 'write_text', forbid_read)
        for status in STATUSES:
            value = build(v1_request, 'p', 'm', TEXT, status, provider_run_id='run')
            assert validate(value) == value
        with pytest.raises(VisionContractError):
            build(v1_request, 'p', 'm', TEXT, 'supported')
    assert before == {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in paths}
    assert sorted(tmp_path.rglob('*')) == files


def test_stdlib_import_and_validation(v1_request):
    code = ('import json,sys; import tools.vision as v; import tools.query_core.query; '
            "assert not {'fitz','pymupdf','jsonschema','requests','openai'} & sys.modules.keys(); "
            'o=v.build_vision_context_observation(json.loads(sys.argv[1]),"p","m","text","unresolved",provider_run_id="run"); '
            'assert v.validate_vision_context_observation(o)==o')
    subprocess.run([sys.executable, '-S', '-c', code, canonical(v1_request)], check=True)
